// Generated by npm run images:optimize. Original workbook image URLs remain supported.
export const menuImageManifest: Record<string, Record<number, string>> = {
  "assets/images/Items/ Halloumi Mezze Bowl.jpg": {
    "480": "assets/images/menu-optimized/80d4bf4ec137-480.webp",
    "960": "assets/images/menu-optimized/80d4bf4ec137-960.webp",
    "1440": "assets/images/menu-optimized/80d4bf4ec137-1440.webp"
  },
  "assets/images/Items/Bataattiranskalaiset.jpg": {
    "480": "assets/images/menu-optimized/78cfc2e9af82-480.webp",
    "960": "assets/images/menu-optimized/78cfc2e9af82-960.webp",
    "1440": "assets/images/menu-optimized/78cfc2e9af82-1440.webp"
  },
  "assets/images/Items/Brokkoli & Hummus .jpg": {
    "480": "assets/images/menu-optimized/ee01a5377b85-480.webp",
    "960": "assets/images/menu-optimized/ee01a5377b85-960.webp",
    "1440": "assets/images/menu-optimized/ee01a5377b85-1440.webp"
  },
  "assets/images/Items/Döner Iskander Bowl Kanalla Ateria.jpg": {
    "480": "assets/images/menu-optimized/dfdc682db132-480.webp",
    "960": "assets/images/menu-optimized/dfdc682db132-960.webp",
    "1440": "assets/images/menu-optimized/dfdc682db132-1440.webp"
  },
  "assets/images/Items/Döner Iskander Bowl Kanalla.jpg": {
    "480": "assets/images/menu-optimized/ab3defb8fc5b-480.webp",
    "960": "assets/images/menu-optimized/ab3defb8fc5b-960.webp",
    "1440": "assets/images/menu-optimized/ab3defb8fc5b-1440.webp"
  },
  "assets/images/Items/Döner Iskander Bowl Naudalla Ateria.jpg": {
    "480": "assets/images/menu-optimized/4f57dd7bbfce-480.webp",
    "960": "assets/images/menu-optimized/4f57dd7bbfce-960.webp",
    "1440": "assets/images/menu-optimized/4f57dd7bbfce-1440.webp"
  },
  "assets/images/Items/Döner Iskander Bowl Naudalla.jpg": {
    "480": "assets/images/menu-optimized/c23ec7fbb580-480.webp",
    "960": "assets/images/menu-optimized/c23ec7fbb580-960.webp",
    "1440": "assets/images/menu-optimized/c23ec7fbb580-1440.webp"
  },
  "assets/images/Items/Döner Ranskalaiset Bowl Naudalla Ateria.jpg": {
    "480": "assets/images/menu-optimized/a6e6f9b6f152-480.webp",
    "960": "assets/images/menu-optimized/a6e6f9b6f152-960.webp",
    "1440": "assets/images/menu-optimized/a6e6f9b6f152-1440.webp"
  },
  "assets/images/Items/Döner Ranskalaiset Bowl Naudalla.jpg": {
    "480": "assets/images/menu-optimized/548303d6aae2-480.webp",
    "960": "assets/images/menu-optimized/548303d6aae2-960.webp",
    "1440": "assets/images/menu-optimized/548303d6aae2-1440.webp"
  },
  "assets/images/Items/Döner Riisi Bowl Kanalla Ateria.jpg": {
    "480": "assets/images/menu-optimized/32ee6f98cb5a-480.webp",
    "960": "assets/images/menu-optimized/32ee6f98cb5a-960.webp",
    "1440": "assets/images/menu-optimized/32ee6f98cb5a-1440.webp"
  },
  "assets/images/Items/Döner Riisi Bowl Kanalla.jpg": {
    "480": "assets/images/menu-optimized/1a1c8af765bd-480.webp",
    "960": "assets/images/menu-optimized/1a1c8af765bd-960.webp",
    "1440": "assets/images/menu-optimized/1a1c8af765bd-1440.webp"
  },
  "assets/images/Items/Döner Riisi Bowl Naudalla Ateria.jpg": {
    "480": "assets/images/menu-optimized/96a64f63a9d0-480.webp",
    "960": "assets/images/menu-optimized/96a64f63a9d0-960.webp",
    "1440": "assets/images/menu-optimized/96a64f63a9d0-1440.webp"
  },
  "assets/images/Items/Döner Riisi Bowl Naudalla.jpg": {
    "480": "assets/images/menu-optimized/1e19c6eb8fc6-480.webp",
    "960": "assets/images/menu-optimized/1e19c6eb8fc6-960.webp",
    "1440": "assets/images/menu-optimized/1e19c6eb8fc6-1440.webp"
  },
  "assets/images/Items/Falafelit & Hummus.jpg": {
    "480": "assets/images/menu-optimized/f55fde5ed7b0-480.webp",
    "960": "assets/images/menu-optimized/f55fde5ed7b0-960.webp",
    "1440": "assets/images/menu-optimized/f55fde5ed7b0-1440.webp"
  },
  "assets/images/Items/Feta Mezze Bowl Ateria.jpg": {
    "480": "assets/images/menu-optimized/82b8183d10e8-480.webp",
    "960": "assets/images/menu-optimized/82b8183d10e8-960.webp",
    "1440": "assets/images/menu-optimized/82b8183d10e8-1440.webp"
  },
  "assets/images/Items/Feta Mezze Bowl.jpg": {
    "480": "assets/images/menu-optimized/13d126a68e84-480.webp",
    "960": "assets/images/menu-optimized/13d126a68e84-960.webp",
    "1440": "assets/images/menu-optimized/13d126a68e84-1440.webp"
  },
  "assets/images/Items/Halloumiranskalaiset.jpg": {
    "480": "assets/images/menu-optimized/14ce4165170a-480.webp",
    "960": "assets/images/menu-optimized/14ce4165170a-960.webp",
    "1440": "assets/images/menu-optimized/14ce4165170a-1440.webp"
  },
  "assets/images/Items/Halloumi–Kana Döner Ateria.jpg": {
    "480": "assets/images/menu-optimized/e778cadc5ce6-480.webp",
    "960": "assets/images/menu-optimized/e778cadc5ce6-960.webp",
    "1440": "assets/images/menu-optimized/e778cadc5ce6-1440.webp"
  },
  "assets/images/Items/Halloumi–Nauta Döner Ateria.jpg": {
    "480": "assets/images/menu-optimized/47cc9048ce3a-480.webp",
    "960": "assets/images/menu-optimized/47cc9048ce3a-960.webp",
    "1440": "assets/images/menu-optimized/47cc9048ce3a-1440.webp"
  },
  "assets/images/Items/Halloumi–Nauta Döner.jpg": {
    "480": "assets/images/menu-optimized/9ef4bd0f7197-480.webp",
    "960": "assets/images/menu-optimized/9ef4bd0f7197-960.webp",
    "1440": "assets/images/menu-optimized/9ef4bd0f7197-1440.webp"
  },
  "assets/images/Items/Kana Döner Ateria.jpg": {
    "480": "assets/images/menu-optimized/11e6ed0a5551-480.webp",
    "960": "assets/images/menu-optimized/11e6ed0a5551-960.webp",
    "1440": "assets/images/menu-optimized/11e6ed0a5551-1440.webp"
  },
  "assets/images/Items/Kana Döner Mezze Bowl Ateria.jpg": {
    "480": "assets/images/menu-optimized/da7772de6c9a-480.webp",
    "960": "assets/images/menu-optimized/da7772de6c9a-960.webp",
    "1440": "assets/images/menu-optimized/da7772de6c9a-1440.webp"
  },
  "assets/images/Items/Kana Döner Mezze Bowl.jpg": {
    "480": "assets/images/menu-optimized/2673243a7af5-480.webp",
    "960": "assets/images/menu-optimized/2673243a7af5-960.webp",
    "1440": "assets/images/menu-optimized/2673243a7af5-1440.webp"
  },
  "assets/images/Items/Kana Döner Ranskalaiset Bowl Ateria.jpg": {
    "480": "assets/images/menu-optimized/c3bb7efc4bff-480.webp",
    "960": "assets/images/menu-optimized/c3bb7efc4bff-960.webp",
    "1440": "assets/images/menu-optimized/c3bb7efc4bff-1440.webp"
  },
  "assets/images/Items/Kana Döner Ranskalaiset Bowl.jpg": {
    "480": "assets/images/menu-optimized/4823e9ee3760-480.webp",
    "960": "assets/images/menu-optimized/4823e9ee3760-960.webp",
    "1440": "assets/images/menu-optimized/4823e9ee3760-1440.webp"
  },
  "assets/images/Items/Kana Döner.jpg": {
    "480": "assets/images/menu-optimized/84631fc95157-480.webp",
    "960": "assets/images/menu-optimized/84631fc95157-960.webp",
    "1440": "assets/images/menu-optimized/84631fc95157-1440.webp"
  },
  "assets/images/Items/Kana Wrap Ateria.jpg": {
    "480": "assets/images/menu-optimized/ffb2d2b16045-480.webp",
    "960": "assets/images/menu-optimized/ffb2d2b16045-960.webp",
    "1440": "assets/images/menu-optimized/ffb2d2b16045-1440.webp"
  },
  "assets/images/Items/Kana Wrap.jpg": {
    "480": "assets/images/menu-optimized/7b4fa1dd0618-480.webp",
    "960": "assets/images/menu-optimized/7b4fa1dd0618-960.webp",
    "1440": "assets/images/menu-optimized/7b4fa1dd0618-1440.webp"
  },
  "assets/images/Items/Kasvis–Halloumi Ateria.jpg": {
    "480": "assets/images/menu-optimized/8a941ef5fd0a-480.webp",
    "960": "assets/images/menu-optimized/8a941ef5fd0a-960.webp",
    "1440": "assets/images/menu-optimized/8a941ef5fd0a-1440.webp"
  },
  "assets/images/Items/Kasvis–Halloumi.jpg": {
    "480": "assets/images/menu-optimized/8f5da43af4fc-480.webp",
    "960": "assets/images/menu-optimized/8f5da43af4fc-960.webp",
    "1440": "assets/images/menu-optimized/8f5da43af4fc-1440.webp"
  },
  "assets/images/Items/Kukkakaali & Hummus .jpg": {
    "480": "assets/images/menu-optimized/7f096585a3bd-480.webp",
    "960": "assets/images/menu-optimized/7f096585a3bd-960.webp",
    "1440": "assets/images/menu-optimized/7f096585a3bd-1440.webp"
  },
  "assets/images/Items/Munakoiso – Brokkoli Ateria.jpg": {
    "480": "assets/images/menu-optimized/6f3858b849f4-480.webp",
    "960": "assets/images/menu-optimized/6f3858b849f4-960.webp",
    "1440": "assets/images/menu-optimized/6f3858b849f4-1440.webp"
  },
  "assets/images/Items/Munakoiso – Brokkoli Pita.jpg": {
    "480": "assets/images/menu-optimized/21823fe17b2e-480.webp",
    "960": "assets/images/menu-optimized/21823fe17b2e-960.webp",
    "1440": "assets/images/menu-optimized/21823fe17b2e-1440.webp"
  },
  "assets/images/Items/Munakoiso–Kukkakaali Ateria.jpg": {
    "480": "assets/images/menu-optimized/1e50fe05bff2-480.webp",
    "960": "assets/images/menu-optimized/1e50fe05bff2-960.webp",
    "1440": "assets/images/menu-optimized/1e50fe05bff2-1440.webp"
  },
  "assets/images/Items/Munakoiso–Kukkakaali Pita.jpg": {
    "480": "assets/images/menu-optimized/8641452203de-480.webp",
    "960": "assets/images/menu-optimized/8641452203de-960.webp",
    "1440": "assets/images/menu-optimized/8641452203de-1440.webp"
  },
  "assets/images/Items/Nauta Döner Ateria.jpg": {
    "480": "assets/images/menu-optimized/6569f0af39b5-480.webp",
    "960": "assets/images/menu-optimized/6569f0af39b5-960.webp",
    "1440": "assets/images/menu-optimized/6569f0af39b5-1440.webp"
  },
  "assets/images/Items/Nauta Döner Mezze Bowl Ateria.jpg": {
    "480": "assets/images/menu-optimized/6cdfebd5117f-480.webp",
    "960": "assets/images/menu-optimized/6cdfebd5117f-960.webp",
    "1440": "assets/images/menu-optimized/6cdfebd5117f-1440.webp"
  },
  "assets/images/Items/Nauta Döner Mezze Bowl.jpg": {
    "480": "assets/images/menu-optimized/1d442be0c71c-480.webp",
    "960": "assets/images/menu-optimized/1d442be0c71c-960.webp",
    "1440": "assets/images/menu-optimized/1d442be0c71c-1440.webp"
  },
  "assets/images/Items/Nauta Döner.jpg": {
    "480": "assets/images/menu-optimized/718207d54355-480.webp",
    "960": "assets/images/menu-optimized/718207d54355-960.webp",
    "1440": "assets/images/menu-optimized/718207d54355-1440.webp"
  },
  "assets/images/Items/Ranskalaiset.jpg": {
    "480": "assets/images/menu-optimized/b600ec0dc08e-480.webp",
    "960": "assets/images/menu-optimized/b600ec0dc08e-960.webp",
    "1440": "assets/images/menu-optimized/b600ec0dc08e-1440.webp"
  },
  "assets/images/Items/Talon Vegaaninen Ateria.jpg": {
    "480": "assets/images/menu-optimized/1cde52acd65a-480.webp",
    "960": "assets/images/menu-optimized/1cde52acd65a-960.webp",
    "1440": "assets/images/menu-optimized/1cde52acd65a-1440.webp"
  },
  "assets/images/Items/Talon Vegaaninen.jpg": {
    "480": "assets/images/menu-optimized/7109306d5281-480.webp",
    "960": "assets/images/menu-optimized/7109306d5281-960.webp",
    "1440": "assets/images/menu-optimized/7109306d5281-1440.webp"
  },
  "assets/images/Items/Vegan Mezze Bowl Ateria.jpg": {
    "480": "assets/images/menu-optimized/299eac401088-480.webp",
    "960": "assets/images/menu-optimized/299eac401088-960.webp",
    "1440": "assets/images/menu-optimized/299eac401088-1440.webp"
  },
  "assets/images/Items/Vegan Mezze Bowl.jpg": {
    "480": "assets/images/menu-optimized/add614ec53e7-480.webp",
    "960": "assets/images/menu-optimized/add614ec53e7-960.webp",
    "1440": "assets/images/menu-optimized/add614ec53e7-1440.webp"
  },
  "assets/images/Items/Vuohenjuusto & Kasvis Ateria.jpg": {
    "480": "assets/images/menu-optimized/175d6131b32f-480.webp",
    "960": "assets/images/menu-optimized/175d6131b32f-960.webp",
    "1440": "assets/images/menu-optimized/175d6131b32f-1440.webp"
  },
  "assets/images/Items/Vuohenjuusto & Kasvis.jpg": {
    "480": "assets/images/menu-optimized/2d464acd477c-480.webp",
    "960": "assets/images/menu-optimized/2d464acd477c-960.webp",
    "1440": "assets/images/menu-optimized/2d464acd477c-1440.webp"
  },
  "assets/images/Items/Vuohenjuusto Mezze Bowl Ateria.jpg": {
    "480": "assets/images/menu-optimized/5eb4d649451f-480.webp",
    "960": "assets/images/menu-optimized/5eb4d649451f-960.webp",
    "1440": "assets/images/menu-optimized/5eb4d649451f-1440.webp"
  },
  "assets/images/Items/Vuohenjuusto Mezze Bowl.jpg": {
    "480": "assets/images/menu-optimized/10d4b6bfb777-480.webp",
    "960": "assets/images/menu-optimized/10d4b6bfb777-960.webp",
    "1440": "assets/images/menu-optimized/10d4b6bfb777-1440.webp"
  },
  "assets/images/Fish n Chips.png": {
    "480": "assets/images/menu-optimized/3753aa990d25-480.webp",
    "960": "assets/images/menu-optimized/3753aa990d25-960.webp",
    "1082": "assets/images/menu-optimized/3753aa990d25-1440.webp"
  }
};
